apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "chatjs"
  namespace: "default"
  labels:
    app: "chatjs"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "chatjs"
  template:
    metadata:
      labels:
        app: "chatjs"
    spec:
      containers:
      - name: "github-moterom-chat-nodejs-1"
        image: "gcr.io/kutai-dev/github_moterom_chat-nodejs:latest"
