
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: chatnodejs
  namespace: "default"
  labels:
    app: chatnodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatnodejs
  template:
    metadata:
      labels:
        app: chatnodejs
    spec:
      containers:
      - name: chatnodejs
        image: gcr.io/kutai-dev/github_moterom_chat-nodejs:$SHORT_SHA
---
apiVersion: "autoscaling/v2"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "nginx-1-hpa-pd3r"
  namespace: "default"
  labels:
    app: chatnodejs
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: chatnodejs
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      target:
        type: "Utilization"
        averageUtilization: 80
